### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by timo2o1o**

### CODE REVIEW

**Review by Jusdon — APPROVED** [review]

**Comment by Jusdon** [comment]
Maybe we should change the branch from main to develop?

**Comment by timo2o1o** [comment]
> Hi @timo2o1o Maybe we should change the branch from main to develop?

Yes, lets do that. I'll create another pull request.

**Comment by Jusdon** [comment]
Hi @timo2o1o you can switch the base branch from main to develop over the edit button in the top right corner. ;-)

**Comment by timo2o1o** [comment]
> Hi @timo2o1o you can switch the base branch from main to develop over the edit button in the top right corner. ;-)

Ah, stupid me. I overlooked that one 🙈

**Pull request closed without merging**
