### PR TITLE
Merge some changes to the data model

### PR DESCRIPTION
**Pull request by timo2o1o**
I just want to merge my changes to the data model, so that I have a better starting point for the test data stuff.

### CODE REVIEW

**Review by Jusdon — APPROVED** [review]
It looks good!
I haven't compiled and run it on my PC, but it looks like everything should work!

**Comment by Jusdon** [comment]
Haha you merged it already :D

**Comment by timo2o1o** [comment]
> Haha you merged it already :D

Yes sorry :D. It's just some small stuff and I don't want it to interfere with my test data generation

**Comment by Jusdon** [comment]
No sorry, it's okay :D

**Pull request merged**
